{{- if .Values.github.app.appId }}
apiVersion: v1
kind: Secret
metadata:
  name: github-app-secrets-{{ .Values.user.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  app-id: {{ .Values.github.app.appId | quote }}
  installation-id: {{ .Values.github.app.installationId | quote }}
  private-key: {{ .Values.github.app.privateKey | quote }}
{{- end }}
